name: coconut
channels:
  - conda-forge
dependencies:
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - colorama=0.4.6
  - comm=0.2.2
  - debugpy=1.8.14
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libexpat=2.6.4
  - libffi=3.4.6
  - liblzma=5.6.4
  - libsodium=1.0.20
  - libsqlite=3.49.1
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl=3.5.0
  - packaging=24.2
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=25.0.1
  - prompt-toolkit=3.0.50
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.12.9
  - python-dateutil=2.9.0.post0
  - python_abi=3.12
  - pywin32=307
  - pyzmq=26.4.0
  - setuptools=75.8.2
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - zeromq=4.3.5
  - zipp=3.21.0
  - pip:
      - accelerate==1.6.0
      - aiohappyeyeballs==2.5.0
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - attrs==25.1.0
      - bitsandbytes==0.45.4
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.3.1
      - cut-cross-entropy==25.1.1
      - cycler==0.12.1
      - datasets==3.1.0
      - diffusers==0.32.2
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - filelock==3.17.0
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - hf-transfer==0.1.9
      - huggingface-hub==0.29.2
      - idna==3.10
      - intel-openmp==2021.4.0
      - jinja2==3.1.6
      - kiwisolver==1.4.8
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mkl==2021.4.0
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.4.2
      - numpy==2.2.4
      - pandas==2.2.3
      - peft==0.15.1
      - pillow==11.0.0
      - platformdirs==4.3.6
      - propcache==0.3.0
      - protobuf==3.20.3
      - pyarrow==19.0.1
      - pyparsing==3.2.3
      - pytz==2025.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==14.0.0
      - safetensors==0.5.3
      - sentencepiece==0.2.0
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - shtab==1.7.1
      - smmap==5.0.2
      - sympy==1.13.1
      - tbb==2021.11.0
      - tokenizers==0.21.1
      - torch==2.6.0+cu126
      - torchaudio==2.6.0+cu126
      - torchvision==0.21.0
      - tqdm==4.67.0
      - transformers==4.50.0
      - triton-windows==3.2.0.post17
      - trl==0.15.2
      - typeguard==4.4.2
      - typing-extensions==4.13.0
      - tyro==0.9.18
      - tzdata==2025.1
      - unsloth==2025.3.19
      - unsloth-zoo==2025.3.17
      - urllib3==2.3.0
      - wandb==0.18.7
      - xformers==0.0.29.post3
      - xxhash==3.5.0
      - yarl==1.18.3
